title: wupeihao's Homepage
page-top-title: wupeihao
top-section-bg-text: Be what you wanna be
home-subtitle: wupeihao&ensp;|&ensp;吴培浩
copyright-text: '&copy; wupeihao 2023-2025. All Rights Reserved.'
